import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "@/app/sidebar"; // Assuming Sidebar is already in the right location
import "./globals.css";
import AdminPanelLayout from "@/components/admin-panel/admin-panel-layout";
import { ContentLayout } from "@/components/admin-panel/content-layout";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="djskg">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AdminPanelLayout>
              <ContentLayout title="Test"> </ContentLayout>
          {children}
          </AdminPanelLayout>
      </body>
    </html>
  );
}
